name: Floating Point Test with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t floating-point-test .

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run associative-property > java_output.txt
          
      # Save only the Java output to answer_associativity.txt
      - name: Save results to file
        run: |
          mkdir -p serialized/pushed
          mv java_output.txt serialized/pushed/answer_associativity.txt


      # Step 6: Commit results to the repository
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add serialized/pushed/answer_associativity.txt
            git commit -m "Update answer_associativity.txt with latest results"
            git push
          else
            echo "No changes to commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
