name: Java Floating Point Test

on:
  push:
    branches:
      - main  # Change this if you want it to run on a different branch
  pull_request:
    branches:
      - main  # Run on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Docker if the image is private (optional)
      # Uncomment if the image is in a private registry
      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # Pull and run the Docker container
      - name: Pull and run Docker image
        run: |
          docker pull Humilokaki/associative-property:latest
          docker run Humilokaki/associative-property:latest > output.txt
          
      # Save results to answer_associativity.txt
      - name: Save results to file
        run: |
          echo "Results from the Java program" > answer_associativity.txt
          cat output.txt >> answer_associativity.txt

      # Commit the results to the repository
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add answer_associativity.txt
          git commit -m "Update answer_associativity.txt with latest results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

