name: Java Variability Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t variability-test .

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run variability-test > output.txt
          
      # Move the CSV output to the desired location
      - name: Save results to file
        run: |
          mkdir -p serialized/pushed
          mv output.txt serialized/pushed/  # Move output from the run

      # Commit the results to the repository
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add serialized/pushed/*
            git commit -m "Update results with latest outputs"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
