name: Java Floating Point Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code using the updated version of the action
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest stable version

      # Set up Docker Buildx with updated action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to the latest stable version

      # Build the Docker image with a specified tag
      - name: Build Docker image
        run: |
          docker build -t associative-property:latest .

      # Run the Docker container and save output
      - name: Run Docker container
        run: |
          docker run associative-property:latest > output.txt
          
      # Save results to answer_associativity.txt
      - name: Save results to file
        run: |
          mkdir -p serialized/pushed
          mv output.txt serialized/pushed/answer_associativity.txt

      # Commit the results to the repository
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add serialized/pushed/answer_associativity.txt
            git commit -m "Update answer_associativity.txt with latest results"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
