name: Java Floating Point Test

on:
  push:
    branches:
      - variation-type  # Change this if you want it to run on a different branch
  pull_request:
    branches:
      - variation-type  # Run on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (optional but recommended for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t associative-property .

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run associative-property > output.txt
          
      # Save results to answer_associativity.txt
      - name: Save results to file
        run: |
          echo "Results from the Java program" > serialized/pushed/answer_associativity.txt
          cat output.txt >> serialized/pushed/answer_associativity.txt

      # Commit the results to the repository
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add serialized/pushed/answer_associativity.txt
          git commit -m "Update answer_associativity.txt with latest results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
